-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgGxoZW4CMp+W06jwo
0aXWjraXOYbK3rQVaYOeqiMUFYOgCgYIKoZIzj0DAQehRANCAAT+hIK4xVcuoWQd
rvHZlB6LiAXKEBVsPjD8iTSRckoFXCCjNuQgvSoKprXuPdmS/DePQIrC1G0m4seG
ayqx2MAO
-----END PRIVATE KEY-----